#!/bin/sh
# vim:foldmethod=marker

# Defaults {{{
export BROWSER=/usr/bin/firefox
export EDITOR=nvim
export VISUAL=nvim
# }}}

# XDG {{{
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
# }}}

# Manual cleanup {{{
export CHKTEXRC="$XDG_CONFIG_HOME/chktex"
export INPUTRC="$XDG_CONFIG_HOME/inputrc"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
# }}}

# Programs {{{
export FZF_DEFAULT_COMMAND='rg --files'
# }}}

# Path {{{
export PATH

PATH="$XDG_DATA_HOME/scryer-prolog/target/release:$PATH"

[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
[ -f "$HOME/.ghcup/env" ] && . "$HOME/.ghcup/env"
PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/.bin:$PATH"
PATH="$HOME/.scripts:$PATH"
#}}}

[ -n "$BASH_VERSION" ] && [ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"
