#!/bin/sh

# Atuin
# curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | sh

# Rustup
# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# Croc
# curl https://getcroc.schollz.com | bash

sudo dnf install fastfetch openconnect sl -y

python3 -m ensurepip --upgrade
python3 -m pip install --upgrade pip
python3 -m pip install beets beets[fetchart] beets-alternatives beets-describe

sudo dnf install podman-compose -y

sudo dnf install ffmpeg -y

sudo dnf install neovim -y

sudo dnf install rclone -y

sudo dnf install bat fd-find fzf ripgrep tokei -y

[ -f "$HOME/.cargo/env" ] \
  && . "$HOME/.cargo/env" \
  && cargo install du-dust \
  && cargo install eza \
  && cargo install tealdeer \
  && cargo install zoxide

# Packer
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
