#!/bin/sh

sudo dnf install git-credential-oauth -y

# Rustup
# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# GHCUp
# curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

# Enable for laptops to fix 2 finger scroll on librewolf/firefox
# echo export MOZ_USE_XINPUT2=1 | sudo tee /etc/profile.d/use-xinput2.sh

sudo dnf install dash -y
sudo ln -sf /usr/bin/dash /usr/bin/sh

sudo dnf install fastfetch openconnect sl -y
sudo dnf install playerctl -y

sudo dnf install beets beets-doc beets-plugins -y

sudo dnf install syncthing -y

sudo dnf install kitty -y

sudo dnf install neovim -y

sudo dnf install rclone -y

sudo dnf install inkscape -y

sudo dnf install bat fd-find lsd rg zoxide -y

[ -f "$HOME/.cargo/env" ] \
  && . "$HOME/.cargo/env" \
  && cargo install du-dust # no dust in fedora :(

sudo dnf install clojure julia racket swi-prolog -y

sudo dnf install texlive-scheme-full -y
sudo dnf install zathura -y
sudo dnf install zathura-pdf-poppler -y
sudo dnf install zathura-djvu -y

# Packer
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
