plugins:
- alternatives
- badfiles
- convert
- describe
- duplicates
- edit
- export
- fetchart
- fuzzy
- info
- mbsync
- missing
- replaygain
- scrub
- zero

alternatives:
  opus:
    directory: /mnt/nas/share/k9/Music/OPUS
    query: ""
    formats: opus mp3 aac

badfiles:
  check_on_import: yes

convert:
  copy_album_art: yes
  embed: no

directory:
  /mnt/nas/share/k9/Music/FLAC

edit:
  albumfields: album albumartist albumtype genre

fetchart:
  maxwidth: 500

format_album: "[$year] $albumartist - $album"
format_item: "[$year] $artist - $album - $title - $length"

paths:
  default: $albumartist/[$year] $album%aunique{}/$track $title
  singleton: Non-Album/[$year] $artist/$title
  comp: Compilations/[$year] $album%aunique{}/$track $title

replaygain:
  backend: ffmpeg
  overwrite: yes

sort_album: "albumartist+ year+ album+"
sort_item: "artist+ year+ album+ disc+ track+"

original_date: yes

zero:
  fields: bpm comments lyrics images
  update_database: true
