plugins:
- alternatives
- convert
- duplicates
- edit
- embedart
- fetchart
- fuzzy
- replaygain
- mbsync
- missing

alternatives:
  opus:
    directory: /home/k9guardian/Music/OPUS
    query: ""
    formats: opus

directory:
  /home/k9guardian/Music/FLAC

edit:
  albumfields: album albumartist genre

replaygain:
  backend: ffmpeg

original_date: yes
