plugins: convert embedart fetchart fuzzy replaygain mbsync missing

convert:
  copy_album_art: yes
  format: opus

directory:
  /home/k9guardian/Music/FLAC

replaygain:
  backend: ffmpeg

original_date: yes
