#!/bin/sh
borg create --stats --progress ::{user}@{hostname}:{now} \
  "$HOME/Documents" \
  "$HOME/Pictures" \
  "$HOME/Music" \
  "$HOME/Videos" \
  "$HOME/Games" \
  "$HOME/.config" \
  "$HOME/.local" \
  "$HOME/.gnupg" \
  "$HOME/.password-store" \
  "$HOME/.ssh"
