services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1001
    network_mode: 'host'
    volumes:
      - jellyfin_config:/config:Z
      - jellyfin_cache:/cache:Z
      - /mnt/nas/share:/media:ro,z
    restart: 'unless-stopped'
volumes:
  jellyfin_config:
  jellyfin_cache:
