#!/bin/sh
usage() {
  echo 'Usage: newline (add | remove) [file] ...'
}

if [ $# -eq 0 ]; then
  usage && exit 1
fi

if [ "$1" = 'add' ]; then
  shift && sd -f e '([^\n])$' '$1\n' "$@"
elif [ "$1" = 'remove' ]; then
  shift && sd -f e '\n$' '' "$@"
else
  usage && exit 1
fi
