#!/bin/sh
xdg-open "$*" 2> /dev/null & disown

case "$*" in
  *.pdf|*.djvu)
    # Auto focus zathura
    DESKTOP=$(xdotool get_desktop)
    sleep 0.75
    ZATHURA_WIN=$(
    wmctrl -lx \
      | awk -v desktop=$DESKTOP '$2 == desktop' \
      | grep "zathura" \
      | grep -F -- "$*" \
      | awk '{print $1}'
    )
    wmctrl -i -a $ZATHURA_WIN
    ;;&
esac
