#!/bin/sh
xdg-open "$*" 2> /dev/null & disown

case "$*" in
  *.pdf|*.djvu)
    # Auto focus zathura
    sleep 0.5
    ZATHURA_WIN=$(wmctrl -lx | grep "zathura" | grep -F "$*" | awk '{print $1}')
    echo $ZATHURA_WIN
    wmctrl -ia $ZATHURA_WIN
    ;;&
esac
