#!/bin/sh
pactl unload-module module-echo-cancel
pactl load-module module-echo-cancel aec_method=webrtc aec_args="analog_gain_control=0 digital_gain_control=1" source_name=echocancel
pactl set-default-source echocancel
