#!/bin/sh
TIME=$(date +"%H%M")

if [ "$TIME" -gt 2200 ] || [ "$TIME" -lt 0800 ]; then
  if [ ! -s "$HOME/.local/state/grayscale_status" ]; then
    $(toggle-grayscale)
  fi
else
  if [ -s "$HOME/.local/state/grayscale_status" ]; then
    $(toggle-grayscale)
  fi
fi
