#!/bin/sh
usage() {
  echo 'Usage: newline (add | remove) [file] ...'
}

if [ $# -eq 0 ]; then
  usage && exit 1
fi

if [ "$1" = 'add' ]; then
  shift && sed -i '$a\' "$@"
elif [ "$1" = 'remove' ]; then
  shift && sed -zi 's/\n$//' "$@"
else
  usage && exit 1
fi
