#!/bin/sh
# TODO: Make size/pos independent of screen size, unfocus feh, kill after 3 seconds
COVER="$XDG_CACHE_HOME/spotify-song-info-album-art.jpeg"

wget -qO "$COVER" $(playerctl --player=spotify metadata mpris:artUrl)

feh --geometry +625+150 --title "$(playerctl metadata --format '{{artist}} - {{title}}')" "$COVER"
