#!/usr/bin/env python3

# Adapted from https://github.com/haron/subtitles-shift

import sys
from datetime import datetime, timedelta

def shift_time(ts):
    return (datetime.strptime(ts, '%H:%M:%S,%f') + timedelta(seconds=DELTA)).strftime('%H:%M:%S,%f')[:12]

try:
    DELTA = int(sys.argv[1])

    try:
        file = open(sys.argv[2])
    except:
        file = sys.stdin

    for s in file.readlines():
        if '-->' in s:
            ts1, _, ts2 = s.split()
            ts1 = shift_time(ts1)
            ts2 = shift_time(ts2)
            print(f'{ts1} --> {ts2}')
        else:
            print(s, end='')

    if file is not sys.stdin:
        file.close()
except:
    print('Usage: subrip-offset seconds [infile]')
